runtime: nodejs12
instance_class: F1
automatic_scaling:
  max_instances: 1 
  min_instances: 0
env_variables:
    DB_USER: 
    DB_PASS: 
    DB_NAME: 
    CLOUD_SQL_CONNECTION_NAME: 
beta_settings:
    cloud_sql_instances: 
