steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'chmod'
  args: ['+rwx','./node_modules/.bin/jest']
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
